plugins:
  feature_voting_enabled:
    default: true
    client: true
  feature_voting_show_who_voted:
    default: true
    client: true
  feature_voting_show_votes_on_profile:
    default: true
    client: true
  feature_voting_tl0_vote_limit:
    default: 3
  feature_voting_tl1_vote_limit:
    default: 5
  feature_voting_tl2_vote_limit:
    default: 8
  feature_voting_tl3_vote_limit:
    default: 10
  feature_voting_tl4_vote_limit:
    default: 10
