plugins:
  voting_enabled:
    default: true
    client: true
  voting_show_who_voted:
    default: true
    client: true
  voting_show_votes_on_profile:
    default: true
    client: true
  voting_tl0_vote_limit:
    default: 3
  voting_tl1_vote_limit:
    default: 5
  voting_tl2_vote_limit:
    default: 8
  voting_tl3_vote_limit:
    default: 10
  voting_tl4_vote_limit:
    default: 10
